### ISSUE TITLE
Make Navbar common for an application

### ISSUE THREAD

**Issue by yzhbankov** [zorko-io/zorko-platform#151]
**Problem:**

The navbar of the application is rendered separately for every route, so each route navbar has its own state that significantly complicates state management. Also, the navbar has an identical functionality for every route. Making a common navbar for all the application routes will lead to simplifying. 
 
**Solution:**

Make navbar common for all routes using common layout for private (if necessary public) routes. Implement routing for an application layout content.

**Technical Solution:**

The routing in AppContainer.jsx component can be changed so, it will be two routes in the top level of an application:
```
<Switch>
      <Route path="/login" render={() => <LoginPage />} />
      <PrivateRoute path="/">
        <App />
      </PrivateRoute>
    </Switch>
```
The new intermediate component App.jsx will render Application layout:
```
function App() {
  return (
    <Layout
      headerRender={() => <Header />}
      contentRender={() => (
        <Switch>
          <PrivateRoute path="/example">
            <ExamplesPage />
          </PrivateRoute>
          <PrivateRoute path="/home">
            <HomePage />
          </PrivateRoute>
        </Switch>
      )}
    />
  )
}
```
The Homepage and ExamplesPage could reuse the Layout component without defining headerRender prop.

**Comment by oleksii-yurchenko** [comment]
close
