### ISSUE TITLE
Setup Dev Environment

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#20]
Follow instructions for contribution

**Comment by whiteadam2** [comment]
node 14.15.1 done!

yarn - done!

Doker: I cant understand for what Doker is? I've installed Docker Desktop for Mac. But I really dont understand how Doker connected whith zorko app

I've launched "yarn test" and got a lot of errors on screen bellow
[https://drive.google.com/file/d/1RnRHaHy_ED0aRoA4UaZi9CpDXDOwHQse/view?usp=sharing](url)

**Comment by nesterone** [comment]
Strange that test failed, however the task is done
