### ISSUE TITLE
Spike: Prepare Login page with Tailwind CSS

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#23]
- read about (tailwind css)[https://tailwindcss.com/]
- build a Login page  
- build a Home page (just write hello message)

it's better to provide that already in a code with react, however, because #3 might be not ready it's possible to prep pages in playground withing the tailwind web site  https://play.tailwindcss.com/

**Comment by whiteadam2** [comment]
https://github.com/zorko-io/zorko-platform/pull/24

**Comment by whiteadam2** [comment]
I've made changes and pushed this branch again

**Comment by nesterone** [comment]
just checked in `dev` it works as expected, so closing this one

however, found an issue with code quality, see #36
