### ISSUE TITLE
Investigate tailwind CSS eslint checkers  

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#34]
right now we have an eslint warining in css from tailwind 

Research 

https://www.npmjs.com/package/@jarrodldavis/eslint-plugin-tailwindcss

and 

https://github.com/Idered/eslint-plugin-tailwind

**Comment by yzhbankov** [comment]
@nesterone was fixed in some of the requests

**Comment by yzhbankov** [comment]
@nesterone issue could not be reproduced, I think it could be closed.
