### ISSUE TITLE
Prepare generic component for handling buttons and images

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#64]
```
<Button>
    {showMobileMenu ? <Image shape={'sandwich'}/> : <Image shape={'cross'}/>} 
</Button>
```
_Originally posted by @nesterone in https://github.com/zorko-io/zorko-platform/pull/47#r539958625_

**Comment by whiteadam2** [comment]
I decided make general component ButtonSVG insted of Button, because this component is not siutable for general button. It has only svg without text and inappropriate styles. May be I'll make general button from other example

**Comment by nesterone** [comment]
I don't like `ButtonSVG`, looks like we break here the composability of components.

let's split work into a few phases here 

1. Create Generic Button component, `Button.jsx` and move it to `components/Button.jsx`, no requrements to render images yet
1. Create Image component and put it to `components/Image.jsx`  (incapsulate svg tags and accept shape value as props)
1. Try to replace all '<button>' without images across a project and report about issues 
1. Try to replace button + image component with our new components and report about issues
