### ISSUE TITLE
Create ApiContext and use across a web-portal-client 

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#74]
I want to try the next idea, instead of passing API as static references, let's try to wrap them in an
ApiContext, so the idea is next 

in `index.jsx`

```
...
import {createClient} from '@util-web-api-client'
import {ApiContext} from './api'
import config from './config.js'

const api = createClient({}) // pick and pass some params and interseptors here if needed



```
<ApiContext instance={api} >

</ApiContext>
```

so in useEffect or component, we will do 

```
 const api = useContext(ApiContext)

 useEffect(async () => {
     await api.auth.login()
 })

```

_Originally posted by @nesterone in https://github.com/zorko-io/zorko-platform/pull/71#discussion_r541988964_

**Comment by yzhbankov** [comment]
@nesterone in this case an api client that should be used in effects will be passed as an argument from the component?
