### ISSUE TITLE
Fix NavBar Logout Button

### ISSUE THREAD

**Issue by yzhbankov** [zorko-io/zorko-platform#92]
**Describe the bug**
After user login to the application the home page nuv bar display "Login" button instead of "Logout"

**To Reproduce**
1. Login
2. See NavBar

**Expected behavior**
After user login the button should display info and behave as Logout button

**Screenshots**
![image](https://user-images.githubusercontent.com/13466225/103150194-6752e480-477a-11eb-8d1d-e0506a7df39c.png)

**Comment by oleksii-yurchenko** [comment]
i've just renamed this button yet
